#!/usr/bin/env bun
// Regenerates src/vault-assets.generated.ts by flattening vault-template/crew/**
// and skill/crew-manager/** into the map Wrangler writes into a fresh vault.
// Run automatically before typecheck and build (see package.json). Safe to re-run.
import { readdirSync, readFileSync, statSync, writeFileSync } from "node:fs";
import { join, relative } from "node:path";

const ROOT = join(import.meta.dir, "..", "..", "..");
const OUT = join(import.meta.dir, "..", "src", "vault-assets.generated.ts");

function walk(dir: string, base: string, into: Record<string, string>): void {
  for (const name of readdirSync(dir)) {
    if (name === ".DS_Store") continue;
    const full = join(dir, name);
    if (statSync(full).isDirectory()) {
      walk(full, base, into);
    } else {
      into[relative(base, full).split("\\").join("/")] = readFileSync(full, "utf8");
    }
  }
}

const assets: Record<string, string> = {};
walk(join(ROOT, "vault-template", "crew"), join(ROOT, "vault-template", "crew"), assets);

const skillAssets: Record<string, string> = {};
walk(join(ROOT, "skill", "crew-manager"), join(ROOT, "skill", "crew-manager"), skillAssets);
for (const [rel, content] of Object.entries(skillAssets)) assets[`skills/crew-manager/${rel}`] = content;

const body = Object.entries(assets)
  .sort(([a], [b]) => a.localeCompare(b))
  .map(([rel, content]) => `  ${JSON.stringify(rel)}: ${JSON.stringify(content)},`)
  .join("\n");

writeFileSync(
  OUT,
  `// Generated by scripts/gen-assets.ts. Do not edit by hand.\n` +
    `export const VAULT_ASSETS: Record<string, string> = {\n${body}\n};\n`,
);
console.log(`Wrote ${Object.keys(assets).length} assets to ${relative(ROOT, OUT)}`);
