#!/usr/bin/env bun
// Regenerates src/vault-template-embedded.generated.ts by embedding vault-template/crew/** and
// skill/crew-manager/**, mirroring gen-helpers.ts's pattern exactly. This is what lets `crew init`
// scaffold a project from inside the compiled binary, with no sibling files on disk to read from
// (see gen-helpers.ts's comment for why that matters for `bun build --compile`).
//
// Kept as two separate records, not one merged map, because crew init applies a different
// overwrite policy to each: template files are skip-if-exists (a human may have edited them),
// the crew-manager skill is always refreshed from source (scripts/init-vault.sh's existing
// asymmetry, preserved here).
import { readdirSync, readFileSync, statSync, writeFileSync } from "node:fs";
import { join, relative } from "node:path";

const ROOT = join(import.meta.dir, "..", "..", "..");
const OUT = join(import.meta.dir, "..", "src", "vault-template-embedded.generated.ts");

function walk(dir: string, base: string, into: Record<string, string>): void {
  for (const name of readdirSync(dir)) {
    if (name === ".DS_Store" || name === "__pycache__") continue;
    const full = join(dir, name);
    if (statSync(full).isDirectory()) walk(full, base, into);
    else into[relative(base, full).split("\\").join("/")] = readFileSync(full, "utf8");
  }
}

function literal(assets: Record<string, string>): string {
  return Object.entries(assets)
    .sort(([a], [b]) => a.localeCompare(b))
    .map(([rel, content]) => `  ${JSON.stringify(rel)}: ${JSON.stringify(content)},`)
    .join("\n");
}

const template: Record<string, string> = {};
walk(join(ROOT, "vault-template", "crew"), join(ROOT, "vault-template", "crew"), template);

const skill: Record<string, string> = {};
walk(join(ROOT, "skill", "crew-manager"), join(ROOT, "skill", "crew-manager"), skill);

writeFileSync(
  OUT,
  `// Generated by scripts/gen-vault-template.ts. Do not edit by hand.\n` +
    `export const VAULT_TEMPLATE_ASSETS: Record<string, string> = {\n${literal(template)}\n};\n` +
    `export const CREW_MANAGER_SKILL_ASSETS: Record<string, string> = {\n${literal(skill)}\n};\n`,
);
console.log(
  `Wrote ${Object.keys(template).length} vault-template files and ${Object.keys(skill).length} crew-manager skill files to ${relative(ROOT, OUT)}`,
);
