#!/usr/bin/env bun
// Regenerates src/helpers-embedded.generated.ts by embedding packages/helpers/**/*.
//
// Why this exists: job scripts import their helper via `${CREW_HELPERS}/bun/crew.ts` or
// PYTHONPATH pointing at packages/helpers/python. That path used to be derived from the
// running binary's own script path -- fine for `bun bin/crew.ts` in a checked-out monorepo,
// but meaningless for `bun build --compile`: the compiled binary has no sibling files on disk
// at all (these plain .ts/.py files aren't reachable from crew's own import graph, so the
// bundler never embeds them), and the derived path resolved to a virtual, nonexistent location.
// Embedding the content as strings and materializing it into the vault's own .state/ on first
// use works identically in both dev and compiled mode, and needs no path derivation at all.
import { readdirSync, readFileSync, statSync, writeFileSync } from "node:fs";
import { join, relative } from "node:path";

const ROOT = join(import.meta.dir, "..", "..", "..");
const OUT = join(import.meta.dir, "..", "src", "helpers-embedded.generated.ts");

function walk(dir: string, base: string, into: Record<string, string>): void {
  for (const name of readdirSync(dir)) {
    if (name === ".DS_Store" || name === "__pycache__") continue;
    const full = join(dir, name);
    if (statSync(full).isDirectory()) walk(full, base, into);
    else into[relative(base, full).split("\\").join("/")] = readFileSync(full, "utf8");
  }
}

const assets: Record<string, string> = {};
walk(join(ROOT, "packages", "helpers"), join(ROOT, "packages", "helpers"), assets);

const body = Object.entries(assets)
  .sort(([a], [b]) => a.localeCompare(b))
  .map(([rel, content]) => `  ${JSON.stringify(rel)}: ${JSON.stringify(content)},`)
  .join("\n");

writeFileSync(
  OUT,
  `// Generated by scripts/gen-helpers.ts. Do not edit by hand.\n` +
    `export const HELPER_ASSETS: Record<string, string> = {\n${body}\n};\n`,
);
console.log(`Wrote ${Object.keys(assets).length} helper files to ${relative(ROOT, OUT)}`);
